# Generated by Django 4.2.6 on 2023-10-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Usuario')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
            ],
        ),
    ]
