# Generated by Django 4.1.2 on 2023-11-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(db_column='idAsignatura', primary_key=True, serialize=False, verbose_name='id de asignatura')),
                ('nombre_asignatura', models.CharField(max_length=25, verbose_name='Nombre de Aignatura')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipoUsuario', models.AutoField(db_column='idTipo', primary_key=True, serialize=False, verbose_name='Tipo de ID')),
                ('tipo_usuario', models.CharField(blank=True, default='DEFAULT VALUE', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUser', primary_key=True, serialize=False, verbose_name='id del Usuario')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('pnombre_usuario', models.CharField(max_length=25, verbose_name='Primer Nombre')),
                ('apaterno_usuario', models.CharField(max_length=25, verbose_name='Apellido Usuario')),
                ('direccion_usuario', models.CharField(max_length=50, verbose_name='Direccion del Usuario')),
                ('password_usuario', models.CharField(max_length=50, verbose_name='Contrasenna del Usuario')),
                ('mail_usuario', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mail del Usuario')),
                ('tipo_usuario', models.ForeignKey(blank=True, db_column='idTipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.CharField(db_column='idClase', max_length=15, primary_key=True, serialize=False, verbose_name='id de clase')),
                ('total_clase', models.IntegerField(blank=True, null=True)),
                ('clase_asistida', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_asignatura', models.ForeignKey(blank=True, db_column='idAsignatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
