# Generated by Django 4.2.2 on 2023-10-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipoUsuario', models.AutoField(db_column='idTipo', primary_key=True, serialize=False, verbose_name='Tipo de ID')),
                ('tipo_usuario', models.CharField(blank=True, default='DEFAULT VALUE', max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='mail_usuario',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mail del Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, db_column='idTipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
    ]
