# Generated by Django 4.1.2 on 2023-10-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_usuario',
            field=models.CharField(default=2, max_length=50, verbose_name='Direccion del Usuario'),
            preserve_default=False,
        ),
    ]
