# Generated by Django 4.2.2 on 2023-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
