# Generated by Django 4.1.2 on 2023-11-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='id_profesor',
            field=models.ForeignKey(blank=True, db_column='idProfesor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idProfesor', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_profesor',
            field=models.IntegerField(blank=True, db_column='idProfesor', null=True, unique=True, verbose_name='id del Profesor'),
        ),
    ]
