# Generated by Django 4.1.2 on 2023-12-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.CharField(db_column='idSeccion', max_length=15, primary_key=True, serialize=False, verbose_name='id de seccion')),
            ],
        ),
        migrations.AlterField(
            model_name='clase',
            name='id_clase',
            field=models.AutoField(db_column='idClase', primary_key=True, serialize=False, verbose_name='id de clase'),
        ),
        migrations.AddField(
            model_name='clase',
            name='id_seccion',
            field=models.ForeignKey(blank=True, db_column='idSeccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seccion'),
        ),
    ]
