# Generated by Django 4.2.2 on 2023-11-10 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, db_column='idTipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
    ]
