# Generated by Django 4.2.2 on 2023-10-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipousuario_usuario_mail_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mail_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apaterno_usuario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pnombre_usuario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer nombre'),
        ),
    ]
