# Generated by Django 4.1.2 on 2023-11-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUser', primary_key=True, serialize=False, verbose_name='id del Usuario')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('direccion_usuario', models.CharField(max_length=50, verbose_name='Direccion del Usuario')),
                ('password_usuario', models.CharField(max_length=50, verbose_name='Contrasenna del Usuario')),
                ('mail_usuario', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mail del Usuario')),
                ('tipo_usuario', models.ForeignKey(blank=True, db_column='idTipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
    ]
