# Generated by Django 4.1.2 on 2023-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_direccion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_usuario',
            field=models.CharField(default=1, max_length=50, verbose_name='Contrasenna del Usuario'),
            preserve_default=False,
        ),
    ]
