# Generated by Django 4.1.2 on 2023-12-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seccion_alter_clase_id_clase_clase_id_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id_seccion',
        ),
        migrations.AlterField(
            model_name='clase',
            name='id_clase',
            field=models.CharField(db_column='idClase', max_length=15, primary_key=True, serialize=False, verbose_name='id de clase'),
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
