# Generated by Django 4.2.2 on 2023-10-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_mail_usuario_usuario_apaterno_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apaterno_usuario',
            field=models.CharField(max_length=30, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pnombre_usuario',
            field=models.CharField(max_length=30, verbose_name='Primer nombre'),
        ),
    ]
